### ISSUE TITLE
Flake: TestSyncOperatorGroups/AllNamespaces/CSVPresent/InstallModeNotSupported

### ISSUE THREAD

**Issue by benluddy** [operator-framework/operator-lifecycle-manager#2091]
```INFO[2021-04-08T19:18:51Z] --- FAIL: TestSyncOperatorGroups (1.90s)     
INFO[2021-04-08T19:18:51Z]     --- FAIL: TestSyncOperatorGroups/AllNamespaces/CSVPresent/InstallModeNotSupported (0.17s) 
INFO[2021-04-08T19:18:51Z]         operator_test.go:4477:               
INFO[2021-04-08T19:18:51Z]             	Error Trace:	operator_test.go:4477 
INFO[2021-04-08T19:18:51Z]             	Error:      	Received unexpected error: 
INFO[2021-04-08T19:18:51Z]             	            	clusterroles.rbac.authorization.k8s.io "csv-role" already exists 
INFO[2021-04-08T19:18:51Z]             	Test:       	TestSyncOperatorGroups/AllNamespaces/CSVPresent/InstallModeNotSupported
```

Seen this a couple times now, most recently in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/operator-framework_operator-lifecycle-manager/2090/pull-ci-operator-framework-operator-lifecycle-manager-master-unit/1380237274532286464#1:build-log.txt%3A969.

**Comment by benluddy** [comment]
Another one: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/operator-framework_operator-lifecycle-manager/2104/pull-ci-operator-framework-operator-lifecycle-manager-master-unit/1384220564280840192#1:build-log.txt%3A1064.

**Comment by benluddy** [comment]
Seen downstream here: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_operator-framework-olm/62/pull-ci-openshift-operator-framework-olm-master-unit-olm/1384544819082170368#1:build-log.txt%3A1341.

**Comment by benluddy** [comment]
Saw a new failure in https://github.com/operator-framework/operator-lifecycle-manager/runs/3243630835?check_suite_focus=true#step:5:1356:

```
--- FAIL: TestSyncOperatorGroups (1.42s)
    --- FAIL: TestSyncOperatorGroups/AllNamespaces/CSVPresent/InstallModeNotSupported (0.13s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1161519]

goroutine 16056 [running]:
testing.tRunner.func1.2(0x2dd0640, 0x469f240)
	/opt/hostedtoolcache/go/1.16.6/x64/src/testing/testing.go:1143 +0x49f
testing.tRunner.func1(0xc003491380)
	/opt/hostedtoolcache/go/1.16.6/x64/src/testing/testing.go:1146 +0x695
panic(0x2dd0640, 0x469f240)
	/opt/hostedtoolcache/go/1.16.6/x64/src/runtime/panic.go:971 +0x499
k8s.io/api/rbac/v1.(*ClusterRole).GetLabels(0x0, 0x15)
	<autogenerated>:1 +0x39
github.com/operator-framework/operator-lifecycle-manager/pkg/lib/ownerutil.IsOwnedByKindLabel(0x376d558, 0x0, 0x30c6aa7, 0x15, 0x15)
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/pkg/lib/ownerutil/util.go:241 +0x43
github.com/operator-framework/operator-lifecycle-manager/pkg/lib/ownerutil.GetOwnerByKindLabel(0x376d558, 0x0, 0x30c6aa7, 0x15, 0x8, 0x30c6aa7, 0x15, 0x0, 0x0)
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/pkg/lib/ownerutil/util.go:82 +0x65
github.com/operator-framework/operator-lifecycle-manager/pkg/lib/ownerutil.IsOwnedByLabel(0x376d558, 0x0, 0x376e858, 0xc004c22000, 0xc00142fc20)
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/pkg/lib/ownerutil/util.go:51 +0xcf
github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm.(*Operator).ensureSingletonRBAC(0xc0040ea000, 0x30b7b3e, 0xb, 0xc004c22000, 0x1, 0x0)
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go:537 +0x82a
github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm.(*Operator).ensureRBACInTargetNamespace(0xc0040ea000, 0xc004c22000, 0xc00493f1e0, 0xc00493f1e0, 0x1d)
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go:495 +0x925
github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm.(*Operator).syncClusterServiceVersion(0xc0040ea000, 0x3090a80, 0xc004c22000, 0x0, 0x0)
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go:1185 +0x778
github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm.TestSyncOperatorGroups.func1(0xc003491380)
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/pkg/controller/operators/olm/operator_test.go:4495 +0xb33
testing.tRunner(0xc003491380, 0xc002ff6a80)
	/opt/hostedtoolcache/go/1.16.6/x64/src/testing/testing.go:1193 +0x203
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.16.6/x64/src/testing/testing.go:1238 +0x5d8
```
