### ISSUE TITLE
Panic in produced in the "Install Plan creation with pre existing CRD owners [It]  OnePreExistingCRDOwner" e2e test

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/operator-lifecycle-manager#2439]
## Bug Report

A panic was produced during an e2e test workflow run in https://github.com/operator-framework/operator-lifecycle-manager/pull/2438 when running the installplan-related e2e tests. That PR doesn't touch anything in the installplan testing suite.

The full panic trace logs:

```log
14:38:42.55: UpgradePending (nginx-dm7xg-stable): &ObjectReference{Kind:InstallPlan,Namespace:operators,Name:install-4cpdn,UID:1e03773e-75ac-4a05-a3aa-ce1989a03de7,APIVersion:operators.coreos.com/v1alpha1,ResourceVersion:6142,FieldPath:,}
waiting for sub-nginx-8fzfm to have installplan ref
installplan install-4cpdn is in phase Installing
installplan install-4cpdn is in phase Installing
installplan install-4cpdn is in phase Complete
Install plan install-4cpdn fetched with status Complete
E1109 14:38:46.687870   20587 runtime.go:76] Observed a panic: 
Your test failed.
Ginkgo panics to prevent subsequent assertions from running.
Normally Ginkgo rescues this panic so you shouldn't see it.

But, if you make an assertion in a goroutine, Ginkgo can't capture the panic.
To circumvent this, you should call

	defer GinkgoRecover()

at the top of the goroutine that caused this panic.

goroutine 14 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x2eb25a0, 0x368ab00)
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x86
panic(0x2eb25a0, 0x368ab00)
	/opt/hostedtoolcache/go/1.16.10/x64/src/runtime/panic.go:965 +0x1b9
github.com/onsi/ginkgo.Fail(0xc0007d7900, 0xc08, 0xc001f651e0, 0x1, 0x1)
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:284 +0xc8
github.com/onsi/ginkgo/internal/testingtproxy.(*ginkgoTestingTProxy).Fatalf(0xc0004dc900, 0x336f7f1, 0x2a, 0xc000771630, 0x1, 0x1)
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/onsi/ginkgo/internal/testingtproxy/testing_t_proxy.go:62 +0xc2
github.com/operator-framework/operator-lifecycle-manager/test/e2e.compareResources(0x3740c88, 0xc0004dc900, 0x32dccc0, 0xc00072aa00, 0x32dccc0, 0xc00072ac00)
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/util_test.go:232 +0x16c
github.com/operator-framework/operator-lifecycle-manager/test/e2e.glob..func11.8.1.2(0xc00072ac00, 0x3711a98)
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go:878 +0x7b
github.com/operator-framework/operator-lifecycle-manager/test/e2e.fetchInstallPlanWithNamespace.func1(0xc0012af3e0, 0xc0012af3e0, 0xc0012af3e0)
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go:4074 +0x197
k8s.io/apimachinery/pkg/util/wait.ConditionFunc.WithContext.func1(0x3711a98, 0xc00011e010, 0xc000ede00c, 0x1, 0x2)
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:217 +0x26
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext(0x3711a98, 0xc00011e010, 0xc00181a9a0, 0x0, 0x0, 0x0)
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:230 +0x7f
k8s.io/apimachinery/pkg/util/wait.WaitForWithContext(0x3711a98, 0xc00011e010, 0xc00207edf8, 0xc00181a9a0, 0x0, 0x0)
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:657 +0x159
k8s.io/apimachinery/pkg/util/wait.poll(0x3711a98, 0xc00011e010, 0xc00207ed00, 0xc00207edf8, 0xc00181a9a0, 0x306e2a0, 0xc00181a9a0)
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:591 +0xa5
k8s.io/apimachinery/pkg/util/wait.PollWithContext(0x3711a98, 0xc00011e010, 0x3b9aca00, 0x45d964b800, 0xc00181a9a0, 0x31d4a00, 0x1)
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:455 +0x66
k8s.io/apimachinery/pkg/util/wait.Poll(0x3b9aca00, 0x45d964b800, 0xc000146a50, 0x10, 0x3069da0)
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:440 +0x6f
github.com/operator-framework/operator-lifecycle-manager/test/e2e.fetchInstallPlanWithNamespace(0x3740c88, 0xc0004dc840, 0x371df58, 0xc0009f1bf0, 0xc000a45910, 0xd, 0x7ffea1e18e5c, 0x9, 0xc00181a980, 0xc00072aa00, ...)
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go:4068 +0x113
github.com/operator-framework/operator-lifecycle-manager/test/e2e.fetchInstallPlan(...)
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go:4061
github.com/operator-framework/operator-lifecycle-manager/test/e2e.glob..func11.8.1()
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go:877 +0x2305
github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc00032cf00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113 +0xa3
github.com/onsi/ginkgo/internal/leafnodes.(*runner).run(0xc00032cf00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:64 +0x15c
github.com/onsi/ginkgo/internal/leafnodes.(*ItNode).Run(0xc00060db40, 0x36bff80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/onsi/ginkgo/internal/leafnodes/it_node.go:26 +0x87
github.com/onsi/ginkgo/internal/spec.(*Spec).runSample(0xc0001253b0, 0x0, 0x36bff80, 0xc0003fc340)
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:215 +0x72f
github.com/onsi/ginkgo/internal/spec.(*Spec).Run(0xc0001253b0, 0x36bff80, 0xc0003fc340)
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:138 +0xf2
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec(0xc000b34dc0, 0xc0001253b0, 0x0)
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:200 +0x111
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs(0xc000b34dc0, 0x1)
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:170 +0x147
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run(0xc000b34dc0, 0xc000b7e8c0)
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:66 +0x117
github.com/onsi/ginkgo/internal/suite.(*Suite).Run(0xc0003e0e00, 0x7fd7041be608, 0xc000741080, 0x3326993, 0xa, 0xc000989880, 0x2, 0x2, 0x371df18, 0xc0003fc340, ...)
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/onsi/ginkgo/internal/suite/suite.go:79 +0x546
github.com/onsi/ginkgo.runSpecsWithCustomReporters(0x36c3680, 0xc000741080, 0x3326993, 0xa, 0xc000989860, 0x2, 0x2, 0x2)
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:238 +0x218
github.com/onsi/ginkgo.RunSpecsWithDefaultAndCustomReporters(0x36c3680, 0xc000741080, 0x3326993, 0xa, 0xc000088f20, 0x1, 0x1, 0xf)
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:221 +0x136
github.com/operator-framework/operator-lifecycle-manager/test/e2e.TestEndToEnd(0xc000741080)
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/e2e_test.go:59 +0x296
testing.tRunner(0xc000741080, 0x343c030)
	/opt/hostedtoolcache/go/1.16.10/x64/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.16.10/x64/src/testing/testing.go:1238 +0x2b3
```

Eyeballing that stack trace it looks like the panic was produced when running the [`compareResources(...)` helper function](https://github.com/operator-framework/operator-lifecycle-manager/blob/700d282adbe09cc0b5d84d70411addb7400f9f79/test/e2e/util_test.go#L230). When checking for semantic equality between two resources, and that operation fails, and we attempt to print out the diff between the two resource inputs, a panic is produced. Diving into the apimachinery helper function to determine diff, it appears that function has been deprecated in favor of another diff library from the google organization.

**Comment by akihikokuroda** [comment]
The `compareResources` function doesn't have any return value.  It calls `FatalF` when resources are different.  The `FatalF` calls `panic` inside.  The callers of compareResources expect panic when the comparison fails.  The panic may not be a good way to express the test failure. How about changing the `compareResources` function to return a bool and caller handle the result?

**Comment by timflannagan** [comment]
> How about changing the compareResources function to return a bool and caller handle the result?

That's sounds reasonable to me - basically, return the result of the `equality.Semantic.DeepEqual(expected, actual)` expression and let call sites handle the bool returned:

```go
eq := compareResources(old.Status, new.Status)
Expect(eq).ToBe(True(), "Resource does not match expected value: %s", diff.ObjectDiff(expected, actual))
```

You still retain the ability to produce an object diff using the formatted assertion too, and remove the need for the GinkoT() parameter entirely. It almost feels like a helper function wouldn't be needed anymore, and this logic could be deflated entirely for relevant tests, but it might good to have consistency in how resources are compared throughout the e2e testing packages with a centralized helper function. WDYT?

**Comment by akihikokuroda** [comment]
Putting `equality.Semantic.DeepEqual(expected, actual)` each place looks very clear and easy to read.  I prefer to eliminate the compareResources helper function.

**Comment by akihikokuroda** [comment]
I made a PR https://github.com/operator-framework/operator-lifecycle-manager/pull/2448.   It removes the compareResources helper function.  I can change if it doesn't look good.
