### ISSUE TITLE
operatorhubio-catalog pod always failed to start

### ISSUE THREAD

**Issue by gongzh** [operator-framework/operator-lifecycle-manager#2947]
## Bug Report

**What did you do?**
Following installation guide to install an OLM control plane, by downloading latest release yaml [v0.24.0](https://github.com/operator-framework/operator-lifecycle-manager/releases/tag/v0.24.0)
kubectl create -f crds.yaml
kubectl create -f olm.yaml

**What did you expect to see?**
Control plane will start successfully.

**What did you see instead? Under which circumstances?**
pod olm-operator, catalog-operator and packageserver are running successfully.
pod operatorhubio-catalog always CrashLoopBackOff

operatorhubio-catalog image is: `quay.io/operatorhubio/catalog:latest`

pod operatorhubio-catalog logs:
```
runtime/cgo: pthread_create failed: Operation not permitted
SIGABRT: abort
PC=0x1c08c3c m=0 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: g 0: unknown pc 0x1c08c3c
stack: frame={sp:0x7ffcee506070, fp:0x0} stack=[0x7ffcedd075f0,0x7ffcee506600)
0x00007ffcee505f70:  0x000000000041a8d9 <runtime.sysMapOS+0x0000000000000039>  0x0000000000000000 
0x00007ffcee505f80:  0x00007f6b85bc7000  0x00000000004056c0 <runtime.mmap.func1+0x0000000000000000> 
0x00007ffcee505f90:  0x0000000000000000  0x0000000000000000 
0x00007ffcee505fa0:  0x0000000000407000 <runtime.cgoCheckTypedBlock+0x0000000000000040>  0x00007f6b87dd8000 
0x00007ffcee505fb0:  0x00007ffcee505fe0  0x0000000001bf1570 
0x00007ffcee505fc0:  0x00007f6b87dd8000  0x0000000000471e1e <runtime.callCgoMmap+0x000000000000003e> 
0x00007ffcee505fd0:  0x00007ffcee505fd8  0x00007f6b87dd8000 
0x00007ffcee505fe0:  0x00007ffcee506050  0x0000000001bf1570 
0x00007ffcee505ff0:  0x000000000040570f <runtime.mmap.func1+0x000000000000004f>  0x0000000000471e1e <runtime.callCgoMmap+0x000000000000003e> 
0x00007ffcee506000:  0x00007ffcee506008  0x0000000000000000 
0x00007ffcee506010:  0x0000000000000120  0x000000120042ea6d 
0x00007ffcee506020:  0x0000000001c7e110  0x000000001c000004 
0x00007ffcee506030:  0x0000000000000110  0x0000000000000000 
0x00007ffcee506040:  0x00007ffcee5062c8  0x000000000042ee78 <runtime.(*pageAlloc).allocRange+0x00000000000001d8> 
0x00007ffcee506050:  0x0000000000000004  0x0000003400000012 
0x00007ffcee506060:  0x0000000000000000  0x0000000001c08c2e 
0x00007ffcee506070: <0x0000000000000000  0x000000770000007c 
0x00007ffcee506080:  0x0000005b0000006e  0x0000000000000004 
0x00007ffcee506090:  0x0000000000000000  0x0000000001c44ff1 
0x00007ffcee5060a0:  0x00007f6b85aa6640  0x00007ffcee506380 
0x00007ffcee5060b0:  0x00007ffcee5061ee  0x00007ffcee5061ef 
0x00007ffcee5060c0:  0x0000000000000000  0x0000000001c070b9 
0x00007ffcee5060d0:  0x0000000000800280 <github.com/gogo/protobuf/proto.makeUnmarshalCustomSlice.func1+0x00000000000001e0>  0x0000000000002030 
0x00007ffcee5060e0:  0x00000000003d0f00  0x00007f6b85aa6910 
0x00007ffcee5060f0:  0x00007f6b85aa6910  0x80ea90631219ea00 
0x00007ffcee506100:  0x00000000049913c0  0x0000000000000006 
0x00007ffcee506110:  0x00000000025a001e  0x00007ffcee506440 
0x00007ffcee506120:  0x00000000035d6e00  0x0000000001bfa156 
0x00007ffcee506130:  0x0000000003609be0  0x00000000004013a7 
0x00007ffcee506140:  0x0000000000000020  0x00007f6b85aa6640 
0x00007ffcee506150:  0x0000000000000000  0x00007ffcee506380 
0x00007ffcee506160:  0x00007f6b85aa6640  0x0000000001c07eea 
runtime: g 0: unknown pc 0x1c08c3c
stack: frame={sp:0x7ffcee506070, fp:0x0} stack=[0x7ffcedd075f0,0x7ffcee506600)
0x00007ffcee505f70:  0x000000000041a8d9 <runtime.sysMapOS+0x0000000000000039>  0x0000000000000000 
0x00007ffcee505f80:  0x00007f6b85bc7000  0x00000000004056c0 <runtime.mmap.func1+0x0000000000000000> 
0x00007ffcee505f90:  0x0000000000000000  0x0000000000000000 
0x00007ffcee505fa0:  0x0000000000407000 <runtime.cgoCheckTypedBlock+0x0000000000000040>  0x00007f6b87dd8000 
0x00007ffcee505fb0:  0x00007ffcee505fe0  0x0000000001bf1570 
0x00007ffcee505fc0:  0x00007f6b87dd8000  0x0000000000471e1e <runtime.callCgoMmap+0x000000000000003e> 
0x00007ffcee505fd0:  0x00007ffcee505fd8  0x00007f6b87dd8000 
0x00007ffcee505fe0:  0x00007ffcee506050  0x0000000001bf1570 
0x00007ffcee505ff0:  0x000000000040570f <runtime.mmap.func1+0x000000000000004f>  0x0000000000471e1e <runtime.callCgoMmap+0x000000000000003e> 
0x00007ffcee506000:  0x00007ffcee506008  0x0000000000000000 
0x00007ffcee506010:  0x0000000000000120  0x000000120042ea6d 
0x00007ffcee506020:  0x0000000001c7e110  0x000000001c000004 
0x00007ffcee506030:  0x0000000000000110  0x0000000000000000 
0x00007ffcee506040:  0x00007ffcee5062c8  0x000000000042ee78 <runtime.(*pageAlloc).allocRange+0x00000000000001d8> 
0x00007ffcee506050:  0x0000000000000004  0x0000003400000012 
0x00007ffcee506060:  0x0000000000000000  0x0000000001c08c2e 
0x00007ffcee506070: <0x0000000000000000  0x000000770000007c 
0x00007ffcee506080:  0x0000005b0000006e  0x0000000000000004 
0x00007ffcee506090:  0x0000000000000000  0x0000000001c44ff1 
0x00007ffcee5060a0:  0x00007f6b85aa6640  0x00007ffcee506380 
0x00007ffcee5060b0:  0x00007ffcee5061ee  0x00007ffcee5061ef 
0x00007ffcee5060c0:  0x0000000000000000  0x0000000001c070b9 
0x00007ffcee5060d0:  0x0000000000800280 <github.com/gogo/protobuf/proto.makeUnmarshalCustomSlice.func1+0x00000000000001e0>  0x0000000000002030 
0x00007ffcee5060e0:  0x00000000003d0f00  0x00007f6b85aa6910 
0x00007ffcee5060f0:  0x00007f6b85aa6910  0x80ea90631219ea00 
0x00007ffcee506100:  0x00000000049913c0  0x0000000000000006 
0x00007ffcee506110:  0x00000000025a001e  0x00007ffcee506440 
0x00007ffcee506120:  0x00000000035d6e00  0x0000000001bfa156 
0x00007ffcee506130:  0x0000000003609be0  0x00000000004013a7 
0x00007ffcee506140:  0x0000000000000020  0x00007f6b85aa6640 
0x00007ffcee506150:  0x0000000000000000  0x00007ffcee506380 
0x00007ffcee506160:  0x00007f6b85aa6640  0x0000000001c07eea 

goroutine 1 [running]:
runtime.systemstack_switch()
        /opt/hostedtoolcache/go/1.19.7/x64/src/runtime/asm_amd64.s:459 fp=0xc000074780 sp=0xc000074778 pc=0x46de00
runtime.main()
        /opt/hostedtoolcache/go/1.19.7/x64/src/runtime/proc.go:170 +0x6d fp=0xc0000747e0 sp=0xc000074780 pc=0x43e1ad
runtime.goexit()
        /opt/hostedtoolcache/go/1.19.7/x64/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000747e8 sp=0xc0000747e0 pc=0x470021

rax    0x0
rbx    0x49913c0
rcx    0xffffffffffffffff
rdx    0x6
rdi    0x1
rsi    0x1
rbp    0x1
rsp    0x7ffcee506070
r8     0x7ffcee506140
r9     0x0
r10    0x8
r11    0x246
r12    0x6
r13    0x16
r14    0x35d6e00
r15    0x7f6b85bc735b
rip    0x1c08c3c
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```

**Environment**
* operator-lifecycle-manager version: v0.24.0
* Kubernetes version information: 1.23.6

**Comment by kevinrizza** [comment]
@gongzh What kind of cluster do you have? My first guess is that there's something about your cluster that's preventing the catalog pod from starting successfully.

Fyi that container image is not owned by this project or repository, it's a separate community project that is built from https://github.com/k8s-operatorhub/community-operators, and OLM just distributes it as part of its installation.

**Comment by awgreene** [comment]
For what it's worth, I used the v0.24.0 install script and my cluster seems to be working as expected:
```
curl -L https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.24.0/install.sh -o install.sh
chmod +x install.sh
./install.sh v0.24.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1886  100  1886    0     0   2351      0 --:--:-- --:--:-- --:--:--  2351
customresourcedefinition.apiextensions.k8s.io/catalogsources.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/clusterserviceversions.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/installplans.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/olmconfigs.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/operatorconditions.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/operatorgroups.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/operators.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/subscriptions.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/catalogsources.operators.coreos.com condition met
customresourcedefinition.apiextensions.k8s.io/clusterserviceversions.operators.coreos.com condition met
customresourcedefinition.apiextensions.k8s.io/installplans.operators.coreos.com condition met
customresourcedefinition.apiextensions.k8s.io/olmconfigs.operators.coreos.com condition met
customresourcedefinition.apiextensions.k8s.io/operatorconditions.operators.coreos.com condition met
customresourcedefinition.apiextensions.k8s.io/operatorgroups.operators.coreos.com condition met
customresourcedefinition.apiextensions.k8s.io/operators.operators.coreos.com condition met
customresourcedefinition.apiextensions.k8s.io/subscriptions.operators.coreos.com condition met
namespace/olm created
namespace/operators created
serviceaccount/olm-operator-serviceaccount created
clusterrole.rbac.authorization.k8s.io/system:controller:operator-lifecycle-manager created
clusterrolebinding.rbac.authorization.k8s.io/olm-operator-binding-olm created
olmconfig.operators.coreos.com/cluster created
deployment.apps/olm-operator created
deployment.apps/catalog-operator created
clusterrole.rbac.authorization.k8s.io/aggregate-olm-edit created
clusterrole.rbac.authorization.k8s.io/aggregate-olm-view created
operatorgroup.operators.coreos.com/global-operators created
operatorgroup.operators.coreos.com/olm-operators created
clusterserviceversion.operators.coreos.com/packageserver created
catalogsource.operators.coreos.com/operatorhubio-catalog created
Waiting for deployment spec update to be observed...
Waiting for deployment spec update to be observed...
Waiting for deployment "olm-operator" rollout to finish: 0 out of 1 new replicas have been updated...
Waiting for deployment "olm-operator" rollout to finish: 0 of 1 updated replicas are available...
deployment "olm-operator" successfully rolled out
deployment "catalog-operator" successfully rolled out
Package server phase: Installing
Package server phase: Succeeded
deployment "packageserver" successfully rolled out
```

The pods in the olm namespace:
```
k get pods -n olm
NAME                                READY   STATUS    RESTARTS   AGE
catalog-operator-655fb46cd4-th25l   1/1     Running   0          2m30s
olm-operator-67fdb4b99d-ckshb       1/1     Running   0          2m30s
operatorhubio-catalog-84gx2         1/1     Running   0          2m15s
packageserver-64bccbcbbc-rpczr      1/1     Running   0          2m15s
packageserver-64bccbcbbc-tvtps      1/1     Running   0          2m15s
```

**Comment by gongzh** [comment]
@awgreene Thanks for your verification.
I followed your steps installing olm by using install.sh script again, and operatorhubio-catalog pod still goes into CrashLoopBackOff and Error status loop, the watching output is as below:
```
k get pods -n olm -w
NAME                                READY   STATUS             RESTARTS      AGE
catalog-operator-588cbf94df-pbvf4   1/1     Running            0             2m46s
olm-operator-6998c47f-6smts         1/1     Running            0             2m46s
operatorhubio-catalog-2vv84         0/1     CrashLoopBackOff   1 (17s ago)   2m44s
packageserver-857585b567-554gx      1/1     Running            0             2m39s
packageserver-857585b567-9lj8k      1/1     Running            0             2m39s
operatorhubio-catalog-2vv84         0/1     Error              2 (21s ago)   2m48s
operatorhubio-catalog-2vv84         0/1     CrashLoopBackOff   2 (2s ago)    2m50s
operatorhubio-catalog-2vv84         0/1     Error              3 (35s ago)   3m23s
operatorhubio-catalog-2vv84         0/1     CrashLoopBackOff   3 (8s ago)    3m30s
operatorhubio-catalog-2vv84         0/1     Error              4 (52s ago)   4m14s
```

I'm wondering if there's any specific requirements of k8s cluster configurations?
(PS: my k8s cluster is installed by binaries, not by kubeadm or kind.)

**Comment by gongzh** [comment]
After some investigation, I've found the error message is about seccomp feature of container runtime:
```
runtime/cgo: pthread_create failed: Operation not permitted
SIGABRT: abort
```
The above error message is because the dockerd version is too old.

After upgrading docker version to latest, quay.io/operatorhubio/catalog:latest can start successfully.
Latest version of containerd runtime is also ok.

So it's a basic requirement of image quay.io/operatorhubio/catalog to start.

@kevinrizza @awgreene Thanks for your help!

**Comment by gongzh** [comment]
After some investigation, I found the error message below when starting `quay.io/operatorhubio/catalog:latest`:
```
runtime/cgo: pthread_create failed: Operation not permitted
SIGABRT: abort
PC=0x1c08c3c m=0 sigcode=18446744073709551610
```
is related to kernel seccomp feature.

1. my dockerd version is too old, so "docker run" will fail.
2. my kubelet version is too old, there's no `--seccomp-default` paramater, no feature-gates `SeccompDefault`

after upgrading dockerd version and kubernetes version, and also tested latest containerd, quay.io/operatorhubio/catalog:latest can start correctly.

@kevinrizza @awgreene Thanks for your help!

**Comment by freemankevin** [comment]
Using version: `v0.22.0`, encountered the same problem.
```shell
 runtime/cgo: pthread_create failed: Operation not permitted

 SIGABRT: abort

 PC=0x1caf90c m=0 sigcode=18446744073709551610

 

 goroutine 0 [idle]:

 runtime: g 0: unknown pc 0x1caf90c

 stack: frame={sp:0x7fff5a9b8cf0, fp:0x0} stack=[0x7fff5a1ba270,0x7fff5a9b9280)

 0x00007fff5a9b8bf0:  0x000000000041a8f9 <runtime.sysMapOS+0x0000000000000039>  0x0000000000000000 

 0x00007fff5a9b8c00:  0x00007f01aaf06000  0x000000000041a885 <runtime.sysHugePageOS+0x0000000000000065> 
```
My docker/k8s version：
```shell
root@ubuntu:~/k8/olm/v0.22.0# kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.17", GitCommit:"953be8927218ec8067e1af2641e540238ffd7576", GitTreeState:"clean", BuildDate:"2023-02-22T13:34:27Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.17", GitCommit:"953be8927218ec8067e1af2641e540238ffd7576", GitTreeState:"clean", BuildDate:"2023-02-22T13:27:46Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
root@ubuntu:~/k8/olm/v0.22.0#
root@ubuntu:~/k8/olm/v0.22.0# docker version
Client:
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:50:40 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:55:09 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.1.1
  GitCommit:        v1.1.0-20-g52de29d7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

The same error is reported when using the new version  `v0.25.0`.
```shell
 runtime/cgo: pthread_create failed: Operation not permitted

 SIGABRT: abort

 PC=0x1caf90c m=0 sigcode=18446744073709551610

 

 goroutine 0 [idle]:

 runtime: g 0: unknown pc 0x1caf90c

 stack: frame={sp:0x7fffdf45cfa0, fp:0x0} stack=[0x7fffdec5e520,0x7fffdf45d530)

 0x00007fffdf45cea0:  0x000000000041a8f9 <runtime.sysMapOS+0x0000000000000039>  0x0000000000000000 

 0x00007fffdf45ceb0:  0x00007f25d1312000  0x000000000041a885 <runtime.sysHugePageOS+0x0000000000000065> 

 0x00007fffdf45cec0:  0x00007f25d3600000  0x0000000000200000 

 0x00007fffdf45ced0:  0x000000000000000e  0x00007f2500000000 

 0x00007fffdf45cee0:  0x00007fffdf45cf10  0x0000000001c98240 

 0x00007fffdf45cef0:  0x00007f25d3523000  0x00000000004722de <runtime.callCgoMmap+0x000000000000003e> 

 0x00007fffdf45cf00:  0x00007fffdf45cf08  0x00007f25d3523000 

 0x00007fffdf45cf10:  0x00007fffdf45cf80  0x0000000001c98240 

 0x00007fffdf45cf20:  0x000000000040572f <runtime.mmap.func1+0x000000000000004f>  0x00000000004722de <runtime.callCgoMmap+0x000000000000003e> 

 0x00007fffdf45cf30:  0x00007fffdf45cf38  0x0000000000000000 

 0x00007fffdf45cf40:  0x0000000000000120  0x000000120042eaad 

 0x00007fffdf45cf50:  0x0000000001d24dd0  0x000000001c000004 

 0x00007fffdf45cf60:  0x0000000000000110  0x0000000000000000 

 0x00007fffdf45cf70:  0x00007fffdf45d1f8  0x000000000042eeb8 <runtime.(*pageAlloc).allocRange+0x00000000000001d8> 

 0x00007fffdf45cf80:  0x0000000000000004  0x0000003400000012 

 0x00007fffdf45cf90:  0x0000000000000000  0x0000000001caf8fe 

 0x00007fffdf45cfa0: <0x0000000000000000  0x000000770000007c 

 0x00007fffdf45cfb0:  0x0000005b0000006e  0x0000000000000004 

 0x00007fffdf45cfc0:  0x0000000000000000  0x0000000001cebcb1 

 0x00007fffdf45cfd0:  0x00007f25d11f1640  0x00007fffdf45d2b0 

 0x00007fffdf45cfe0:  0x00007fffdf45d11e  0x00007fffdf45d11f 

 0x00007fffdf45cff0:  0x0000000000000000  0x0000000001cadd89 

 0x00007fffdf45d000:  0x0000000000800280 <crypto/tls.md5SHA1Hash+0x0000000000000020>  0x0000000000002030 

 0x00007fffdf45d010:  0x00000000003d0f00  0x00007f25d11f1910 

 0x00007fffdf45d020:  0x00007f25d11f1910  0x40a4f5e846417b00 

 0x00007fffdf45d030:  0x00000000038453c0  0x0000000000000006 

 0x00007fffdf45d040:  0x000000000269f96e  0x00007fffdf45d370 

 0x00007fffdf45d050:  0x0000000003778ca0  0x0000000001ca0e26 

 0x00007fffdf45d060:  0x00000000037aba80  0x00000000004013c1 

 0x00007fffdf45d070:  0x0000000000000020  0x00007f25d11f1640 

 0x00007fffdf45d080:  0x0000000000000000  0x00007fffdf45d2b0 

 0x00007fffdf45d090:  0x00007f25d11f1640  0x0000000001caebba 

 runtime: g 0: unknown pc 0x1caf90c

 stack: frame={sp:0x7fffdf45cfa0, fp:0x0} stack=[0x7fffdec5e520,0x7fffdf45d530)

 0x00007fffdf45cea0:  0x000000000041a8f9 <runtime.sysMapOS+0x0000000000000039>  0x0000000000000000 

 0x00007fffdf45ceb0:  0x00007f25d1312000  0x000000000041a885 <runtime.sysHugePageOS+0x0000000000000065> 

 0x00007fffdf45cec0:  0x00007f25d3600000  0x0000000000200000 

 0x00007fffdf45ced0:  0x000000000000000e  0x00007f2500000000 

 0x00007fffdf45cee0:  0x00007fffdf45cf10  0x0000000001c98240 

 0x00007fffdf45cef0:  0x00007f25d3523000  0x00000000004722de <runtime.callCgoMmap+0x000000000000003e> 

 0x00007fffdf45cf00:  0x00007fffdf45cf08  0x00007f25d3523000 

 0x00007fffdf45cf10:  0x00007fffdf45cf80  0x0000000001c98240 

 0x00007fffdf45cf20:  0x000000000040572f <runtime.mmap.func1+0x000000000000004f>  0x00000000004722de <runtime.callCgoMmap+0x000000000000003e> 

 0x00007fffdf45cf30:  0x00007fffdf45cf38  0x0000000000000000 

 0x00007fffdf45cf40:  0x0000000000000120  0x000000120042eaad 

 0x00007fffdf45cf50:  0x0000000001d24dd0  0x000000001c000004 

 0x00007fffdf45cf60:  0x0000000000000110  0x0000000000000000 

 0x00007fffdf45cf70:  0x00007fffdf45d1f8  0x000000000042eeb8 <runtime.(*pageAlloc).allocRange+0x00000000000001d8> 

 0x00007fffdf45cf80:  0x0000000000000004  0x0000003400000012 

 0x00007fffdf45cf90:  0x0000000000000000  0x0000000001caf8fe 

 0x00007fffdf45cfa0: <0x0000000000000000  0x000000770000007c 

 0x00007fffdf45cfb0:  0x0000005b0000006e  0x0000000000000004 

 0x00007fffdf45cfc0:  0x0000000000000000  0x0000000001cebcb1 

 0x00007fffdf45cfd0:  0x00007f25d11f1640  0x00007fffdf45d2b0 

 0x00007fffdf45cfe0:  0x00007fffdf45d11e  0x00007fffdf45d11f 

 0x00007fffdf45cff0:  0x0000000000000000  0x0000000001cadd89 

 0x00007fffdf45d000:  0x0000000000800280 <crypto/tls.md5SHA1Hash+0x0000000000000020>  0x0000000000002030 

 0x00007fffdf45d010:  0x00000000003d0f00  0x00007f25d11f1910 

 0x00007fffdf45d020:  0x00007f25d11f1910  0x40a4f5e846417b00 

 0x00007fffdf45d030:  0x00000000038453c0  0x0000000000000006 

 0x00007fffdf45d040:  0x000000000269f96e  0x00007fffdf45d370 

 0x00007fffdf45d050:  0x0000000003778ca0  0x0000000001ca0e26 

 0x00007fffdf45d060:  0x00000000037aba80  0x00000000004013c1 

 0x00007fffdf45d070:  0x0000000000000020  0x00007f25d11f1640 

 0x00007fffdf45d080:  0x0000000000000000  0x00007fffdf45d2b0 

 0x00007fffdf45d090:  0x00007f25d11f1640  0x0000000001caebba 

 

 goroutine 1 [running]:

 runtime.systemstack_switch()

 	/opt/hostedtoolcache/go/1.19.12/x64/src/runtime/asm_amd64.s:459 fp=0xc000074780 sp=0xc000074778 pc=0x46e2c0

 runtime.main()

 	/opt/hostedtoolcache/go/1.19.12/x64/src/runtime/proc.go:170 +0x6d fp=0xc0000747e0 sp=0xc000074780 pc=0x43e2ad

 runtime.goexit()

 	/opt/hostedtoolcache/go/1.19.12/x64/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000747e8 sp=0xc0000747e0 pc=0x4704e1

 

 rax    0x0

 rbx    0x38453c0

 rcx    0x1caf90c

 rdx    0x6

 rdi    0x1

 rsi    0x1

 rbp    0x1

 rsp    0x7fffdf45cfa0

 r8     0x7fffdf45d070

 r9     0x0

 r10    0x8

 r11    0x246

 r12    0x6

 r13    0x16

 r14    0x3778ca0

 r15    0x7f25d131235b

 rip    0x1caf90c

 rflags 0x246

 cs     0x33

 fs     0x0

 gs     0x0
```
