### ISSUE TITLE
[FLAKE e2e (2)] Operator Group [It] e2e functionality

### ISSUE THREAD

**Issue by tmshort** [operator-framework/operator-lifecycle-manager#3085]
## Flaky Test Report

**Failure Log Link**
[Failure Log](https://github.com/operator-framework/operator-lifecycle-manager/actions/runs/6748278444/job/18346281275#step:5:574)

**Relevant Failure Log**
```
------------------------------
• [FAILED] [2.038 seconds]
Operator Group [It] e2e functionality
/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go:57

  Captured StdOut/StdErr Output >>
  E1103 17:27:56.158640   24870 runtime.go:79] Observed a panic: types.GinkgoError{Heading:"Your Test Panicked", Message:"When you, or your assertion library, calls Ginkgo's Fail(),\nGinkgo panics to prevent subsequent assertions from running.\n\nNormally Ginkgo rescues this panic so you shouldn't see it.\n\nHowever, if you make an assertion in a goroutine, Ginkgo can't capture the panic.\nTo circumvent this, you should call\n\n\tdefer GinkgoRecover()\n\nat the top of the goroutine that caused this panic.\n\nAlternatively, you may have made an assertion outside of a Ginkgo\nleaf node (e.g. in a container node or some out-of-band function) - please move your assertion to\nan appropriate Ginkgo node (e.g. a BeforeSuite, BeforeEach, It, etc...).", DocLink:"mental-model-how-ginkgo-handles-failure", CodeLocation:types.CodeLocation{FileName:"/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go", LineNumber:141, FullStackTrace:"github.com/stretchr/testify/require.ElementsMatch({0x7faac0167c10, 0xc00124e120}, {0x35cd480, 0xc002[577](https://github.com/operator-framework/operator-lifecycle-manager/actions/runs/6748278444/job/18346281275#step:5:578)ec0}, {0x35cd480, 0xc002577ed8}, {0xc00123c680, 0x2, 0x2})\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/stretchr/testify/require/require.go:102 +0xc5\ngithub.com/operator-framework/operator-lifecycle-manager/test/e2e.glob..func20.3.4()\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go:141 +0x1e5\nk8s.io/apimachinery/pkg/util/wait.ConditionFunc.WithContext.func1({0xc002356301, 0x0})\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:109 +0x1b\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext({0x40ae870?, 0xc000128000?}, 0xc00123c7c8?)\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:154 +0x57\nk8s.io/apimachinery/pkg/util/wait.waitForWithContext({0x40ae870, 0xc000128000}, 0xc002af5278, 0x1b71a0a?)\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:207 +0x112\nk8s.io/apimachinery/pkg/util/wait.poll({0x40ae870, 0xc000128000}, 0x8?, 0x1b72745?, 0x345380f?)\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/poll.go:260 +0x9a\nk8s.io/apimachinery/pkg/util/wait.PollWithContext({0x40ae870, 0xc000128000}, 0x0?, 0xc00123c858?, 0x134c4c7?)\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/poll.go:85 +0x47\nk8s.io/apimachinery/pkg/util/wait.Poll(0x3c4eecd?, 0x30?, 0x0?)\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/poll.go:66 +0x50\ngithub.com/operator-framework/operator-lifecycle-manager/test/e2e.glob..func20.3()\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go:135 +0xd08", CustomMessage:""}} (Your Test Panicked
  require.ElementsMatch(GinkgoT(), expectedOperatorGroupStatus.Namespaces, fetched.Status.Namespaces, "have %#v", fetched.Status.Namespaces)
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go:141
    When you, or your assertion library, calls Ginkgo's Fail(),
    Ginkgo panics to prevent subsequent assertions from running.

    Normally Ginkgo rescues this panic so you shouldn't see it.

    However, if you make an assertion in a goroutine, Ginkgo can't capture the
    panic.
    To circumvent this, you should call

    	defer GinkgoRecover()

    at the top of the goroutine that caused this panic.

    Alternatively, you may have made an assertion outside of a Ginkgo
    leaf node (e.g. in a container node or some out-of-band function) - please
    move your assertion to
    an appropriate Ginkgo node (e.g. a BeforeSuite, BeforeEach, It, etc...).

    Learn more at:
    http://onsi.github.io/ginkgo/#mental-model-how-ginkgo-handles-failure
  )
  goroutine 1815 [running]:
  k8s.io/apimachinery/pkg/util/runtime.logPanic({0x39f2760?, 0xc000345b90})
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x99
  k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0?})
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x75
  panic({0x39f2760, 0xc000345b90})
  	/opt/hostedtoolcache/go/1.20.10/x64/src/runtime/panic.go:884 +0x213
  github.com/onsi/ginkgo/v2.Fail({0xc000145600, 0x8a1}, {0xc00116df40?, 0x1?, 0x1?})
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/onsi/ginkgo/v2/core_dsl.go:374 +0x225
  github.com/onsi/ginkgo/v2/internal/testingtproxy.(*ginkgoTestingTProxy).Errorf(0xc00124e120, {0x3bd1ba8?, 0xc00124e120?}, {0xc003ab3d50?, 0x38d0aa0?, 0xc00123c4b0?})
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/onsi/ginkgo/v2/internal/testingtproxy/testing_t_proxy.go:88 +0x77
  github.com/stretchr/testify/assert.Fail({0x7faac0167c58, 0xc00124e120}, {0xc00127dc80, 0x165}, {0xc00123c680, 0x2, 0x2})
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/stretchr/testify/assert/assertions.go:333 +0x378
  github.com/stretchr/testify/assert.ElementsMatch({0x7faac0167c58, 0xc00124e120}, {0x35cd480, 0xc002577ec0}, {0x35cd480, 0xc002577ed8}, {0xc00123c680, 0x2, 0x2})
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/stretchr/testify/assert/assertions.go:1057 +0x1c6
  github.com/stretchr/testify/require.ElementsMatch({0x7faac0167c10, 0xc00124e120}, {0x35cd480, 0xc002577ec0}, {0x35cd480, 0xc002577ed8}, {0xc00123c680, 0x2, 0x2})
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/stretchr/testify/require/require.go:102 +0xc5
  github.com/operator-framework/operator-lifecycle-manager/test/e2e.glob..func20.3.4()
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go:141 +0x1e5
  k8s.io/apimachinery/pkg/util/wait.ConditionFunc.WithContext.func1({0xc002356301, 0x0})
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:109 +0x1b
  k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext({0x40ae870?, 0xc000128000?}, 0xc00123c7c8?)
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:154 +0x57
  k8s.io/apimachinery/pkg/util/wait.waitForWithContext({0x40ae870, 0xc000128000}, 0xc002af5278, 0x1b71a0a?)
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:207 +0x112
  k8s.io/apimachinery/pkg/util/wait.poll({0x40ae870, 0xc000128000}, 0x8?, 0x1b72745?, 0x345380f?)
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/poll.go:260 +0x9a
  k8s.io/apimachinery/pkg/util/wait.PollWithContext({0x40ae870, 0xc000128000}, 0x0?, 0xc00123c858?, 0x134c4c7?)
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/poll.go:85 +0x47
  k8s.io/apimachinery/pkg/util/wait.Poll(0x3c4eecd?, 0x30?, 0x0?)
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/poll.go:66 +0x50
  github.com/operator-framework/operator-lifecycle-manager/test/e2e.glob..func20.3()
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go:135 +0xd08
  github.com/onsi/ginkgo/v2/internal.extractBodyFunction.func3({0x32612d616239342d, 0x65633034642d3436})
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/onsi/ginkgo/v2/internal/node.go:463 +0x1b
  github.com/onsi/ginkgo/v2/internal.(*Suite).runNode.func3()
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/onsi/ginkgo/v2/internal/suite.go:863 +0x98
  created by github.com/onsi/ginkgo/v2/internal.(*Suite).runNode
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/onsi/ginkgo/v2/internal/suite.go:850 +0xd65
  << Captured StdOut/StdErr Output

  Timeline >>
  created the operator-group-e2e-mv54q testing namespace
  17:27:55.7094: Creating CRD
  17:27:55.8229: Creating operator group
  17:27:55.9294: Waiting on operator group to have correct status
  [FAILED] in [It] - /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go:141 @ 11/03/23 17:27:56.943
  cleaning up ephemeral test resources...
  deleting test subscriptions...
  deleting test installplans...
  deleting test catalogsources...
  deleting test crds...
  deleting test csvs...
  test resources deleted
  << Timeline

  [FAILED] 
  	Error Trace:	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go:141
  	            				/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:109
  	            				/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:154
  	            				/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:207
  	            				/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/poll.go:260
  	            				/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/poll.go:85
  	            				/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/poll.go:66
  	            				/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go:135
  	            				/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/onsi/ginkgo/v2/internal/node.go:463
  	            				/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/onsi/ginkgo/v2/internal/suite.go:863
  	            				/opt/hostedtoolcache/go/1.20.10/x64/src/runtime/asm_amd64.s:1[598](https://github.com/operator-framework/operator-lifecycle-manager/actions/runs/6748278444/job/18346281275#step:5:599)
  	Error:      	elements differ
  	            	
  	            	extra elements in list A:
  	            	([]interface {}) (len=1) {
  	            	 (string) (len=36) "operator-group-e2e-mv54q-nrtpk-b2rjw"
  	            	}
  	            	
  	            	
  	            	listA:
  	            	([]string) (len=2) {
  	            	 (string) (len=30) "operator-group-e2e-mv54q-nrtpk",
  	            	 (string) (len=36) "operator-group-e2e-mv54q-nrtpk-b2rjw"
  	            	}
  	            	
  	            	
  	            	listB:
  	            	([]string) (len=1) {
  	            	 (string) (len=30) "operator-group-e2e-mv54q-nrtpk"
  	            	}
  	Test:       	Operator Group e2e functionality
  	Messages:   	have []string{"operator-group-e2e-mv54q-nrtpk"}
  
  In [It] at: /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go:141 @ 11/03/23 17:27:56.943

  Full Stack Trace
    github.com/stretchr/testify/require.ElementsMatch({0x7faac0167c10, 0xc00124e120}, {0x35cd480, 0xc002577ec0}, {0x35cd480, 0xc002577ed8}, {0xc00123c680, 0x2, 0x2})
    	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/stretchr/testify/require/require.go:102 +0xc5
    github.com/operator-framework/operator-lifecycle-manager/test/e2e.glob..func20.3.4()
    	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go:141 +0x1e5
    k8s.io/apimachinery/pkg/util/wait.ConditionFunc.WithContext.func1({0xc002356301, 0x0})
    	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:109 +0x1b
    k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext({0x40ae870?, 0xc000128000?}, 0xc00123c7c8?)
    	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:154 +0x57
    k8s.io/apimachinery/pkg/util/wait.waitForWithContext({0x40ae870, 0xc000128000}, 0xc002af5278, 0x1b71a0a?)
    	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:207 +0x112
    k8s.io/apimachinery/pkg/util/wait.poll({0x40ae870, 0xc000128000}, 0x8?, 0x1b72745?, 0x345380f?)
    	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/poll.go:260 +0x9a
    k8s.io/apimachinery/pkg/util/wait.PollWithContext({0x40ae870, 0xc000128000}, 0x0?, 0xc00123c858?, 0x134c4c7?)
    	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/poll.go:85 +0x47
    k8s.io/apimachinery/pkg/util/wait.Poll(0x3c4eecd?, 0x30?, 0x0?)
    	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/poll.go:66 +0x50
    github.com/operator-framework/operator-lifecycle-manager/test/e2e.glob..func20.3()
    	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go:135 +0xd08
------------------------------
```

**Comment by ncdc** [comment]
It looks like it's because we're using require.ElementsMatch inside a wait.Poll. If we intend to allow the polling to occur, we can't put a testify assertion/requirement inside the condition function.

**Comment by ncdc** [comment]
@tmshort you might want to make this fix in your PR?

**Comment by tmshort** [comment]
> It looks like it's because we're using require.ElementsMatch inside a wait.Poll. If we intend to allow the polling to occur, we can't put a testify assertion/requirement inside the condition function.

Agreed. But `assert` should work, since it returns a `bool`.

**Comment by tmshort** [comment]
> @tmshort you might want to make this fix in your PR?

This doesn't happen very often, in fact, it was the first time I've seen this instances, AFAIR

**Comment by ncdc** [comment]
assertions call t.Fail, so I'd avoid them inside eventually's

**Comment by tmshort** [comment]
> assertions call t.Fail, so I'd avoid them inside eventually's

I was looking at the wrong defintion... :/
